version: 2


base_image: &base_image
  docker:
    - image: 093527149400.dkr.ecr.us-west-2.amazonaws.com/docker-builder:latest

jobs:
  build:
    <<: *base_image
    steps:
      - checkout
      - run: |
          python3 -m venv venv && . ./venv/bin/activate
          python setup.py bdist_wheel
          s3pypi --secret ${PYPI_SECRET} --bucket pypi.people.ai --private

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          context: org-global
